from turtle import *

#module qui dessine une cerise

#fonction qui dessine un rectangle de "pixel"
def rectangle(l,t):
    t.begin_fill()
    for i in range(2):
        t.forward(l*2)
        t.right(90)
        t.forward(l)
        t.right(90)
    t.end_fill()

#fonction qui dessine un carré de "pixel"
def carre(l,t):
    t.begin_fill()
    for i in range(4):
        t.forward(l)
        t.right(90)
    t.end_fill()

#fonction qui effectue un déplacement de la tortue
def deplacement(x,y,t):
    t.up()
    t.goto(x,y)
    t.down()

#fonction qui dessine une cerise en pixel
def cerise(x,y,longueur,t):
    deplacement(x,y,t)
    #on dessine les pixels roses
    t.color("pink")
    rectangle(longueur,t)
    deplacement(x-2*longueur,y-longueur,t)
    rectangle(longueur,t)
    deplacement(x,y-longueur,t)
    rectangle(longueur,t)
    deplacement(x-4*longueur, y-2*longueur,t)
    rectangle(longueur,t)
    deplacement(x-5*longueur, y-3*longueur,t)
    carre(longueur,t)
    deplacement(x-6*longueur, y-4*longueur,t)
    carre(longueur,t)
    deplacement(x-longueur, y-2*longueur,t)
    carre(longueur,t)
    deplacement(x-longueur, y-3*longueur,t)
    carre(longueur,t)
    deplacement(x-2*longueur, y-4*longueur,t)
    carre(longueur,t)
    deplacement(x-3*longueur, y-5*longueur,t)
    carre(longueur,t)
    deplacement(x-3*longueur, y-6*longueur,t)
    carre(longueur,t)
    deplacement(x-7*longueur, y-5*longueur,t)
    carre(longueur,t)

    #on dessine les pixels rouges
    t.color("red")
    deplacement(x-7*longueur, y-4*longueur,t)
    carre(longueur,t)
    deplacement(x-9*longueur, y-4*longueur,t)
    rectangle(longueur,t)
    deplacement(x-10*longueur, y-5*longueur,t)
    carre(longueur,t)
    deplacement(x-9*longueur, y-5*longueur,t)
    rectangle(longueur,t)
    deplacement(x-6*longueur, y-5*longueur,t)
    rectangle(longueur,t)
    deplacement(x-10*longueur, y-6*longueur,t)
    rectangle(longueur,t)
    deplacement(x-8*longueur, y-6*longueur,t)
    rectangle(longueur,t)
    deplacement(x-6*longueur, y-6*longueur,t)
    carre(longueur,t)
    deplacement(x-4*longueur, y-6*longueur,t)
    carre(longueur,t)
    deplacement(x-2*longueur, y-6*longueur,t)
    rectangle(longueur,t)
    deplacement(x-10*longueur, y-7*longueur,t)
    carre(longueur,t)
    deplacement(x-8*longueur, y-7*longueur,t)
    rectangle(longueur,t)
    deplacement(x-5*longueur, y-7*longueur,t)
    rectangle(longueur,t)
    deplacement(x-3*longueur, y-7*longueur,t)
    rectangle(longueur,t)
    deplacement(x-1*longueur, y-7*longueur,t)
    rectangle(longueur,t)
    deplacement(x-10*longueur, y-8*longueur,t)
    rectangle(longueur,t)
    deplacement(x-7*longueur, y-8*longueur,t)
    carre(longueur,t)
    deplacement(x-5*longueur, y-8*longueur,t)
    rectangle(longueur,t)
    deplacement(x-3*longueur, y-8*longueur,t)
    rectangle(longueur,t)
    deplacement(x-1*longueur, y-8*longueur,t)
    rectangle(longueur,t)
    deplacement(x-9*longueur, y-9*longueur,t)
    rectangle(longueur,t)
    deplacement(x-7*longueur, y-9*longueur,t)
    carre(longueur,t)
    deplacement(x-5*longueur, y-9*longueur,t)
    carre(longueur,t)
    deplacement(x-3*longueur, y-9*longueur,t)
    rectangle(longueur,t)
    deplacement(x-1*longueur, y-9*longueur,t)
    rectangle(longueur,t)
    deplacement(x-5*longueur, y-10*longueur,t)
    rectangle(longueur,t)
    deplacement(x-2*longueur, y-10*longueur,t)
    rectangle(longueur,t)
    deplacement(x-1*longueur, y-10*longueur,t)
    carre(longueur,t)
    deplacement(x-4*longueur, y-11*longueur,t)
    rectangle(longueur,t)
    deplacement(x-2*longueur, y-11*longueur,t)
    rectangle(longueur,t)
