from turtle import *

tc = Turtle()
tc.ht()
tc.pensize(4)

#fonction qui effectue un déplacement de la tortue
def deplacement(x,y,t):
    t.up()
    t.goto(x+5,y+10)
    t.down()

# l désigne pour la longueur
# c désigne pour la couleur

#fonction qui dessine l'objet cerise
def ceriseD(x,y,l,c,t):
    deplacement(x+l/5,y,t)
    t.color(c)
    t.begin_fill()
    t.circle(l/10)
    t.end_fill()
    t.left(90)
    t.forward(l/10*2)
    t.setheading(0)
    t.left(60)
    t.forward(l/3)
    t.right(120)
    t.forward(l/3)
    t.right(30)
    t.forward(l/10*2)
    t.setheading(0)
    t.begin_fill()
    t.circle(l/10)
    t.end_fill()
    t.setheading(0)

#fonction qui dessine l'objet pomme
def pomme(x,y,l,c,t):
    deplacement(x+l,y,t)
    t.color(c)
    t.begin_fill()
    t.setheading(-30)
    t.circle(l,240)
    deplacement(x+l,y,t)
    t.setheading(210)
    t.circle(-l,240)
    t.end_fill()
    t.setheading(20)
    t.color("white")
    t.begin_fill()
    t.circle(l,70)
    t.left(110)
    t.circle(l,70)
    t.end_fill()
    t.setheading(0)

#fonction qui dessine l'objet orange
def orange(x,y,l,c,t):
    deplacement(x+l/2,y,t)
    t.color(c)
    t.up()
    t.forward(l/2)
    t.down()
    t.begin_fill()
    t.circle(l)
    t.end_fill()
    t.color("white")
    t.circle(l)
    t.left(90)
    t.up()
    t.forward(l)
    t.down()
    for x in range(0,8):
        t.left(45)
        t.forward(l-1)
        t.backward(l-1)
    t.setheading(0)

#fonction qui dessine l'objet melon
def melon(x,y,l,c,t):
    deplacement(x,y+l,t)
    t.color(c)
    t.setheading(-90)
    t.begin_fill()
    t.circle(l,180)
    t.left(90)
    t.forward(l*2)
    t.end_fill()
    t.forward(-l/2)
    l=l/2
    t.color("brown")
    t.setheading(-90)
    t.begin_fill()
    t.circle(l,180)
    t.left(90)
    t.forward(l*2)
    t.end_fill()
    t.right(180)
    t.forward(l/3)
    t.right(90)
    t.forward(l/3)
    t.left(90)
    t.color("black")
    for i in range(5):
        t.begin_fill()
        t.circle(l/20)
        t.end_fill()
        t.up()
        t.forward(l/3)
        t.down()
    t.setheading(0)

#fonction qui dessine l'objet raisin
def raisin(x,y,l,c,t):
    deplacement(x,y,t)
    t.color(c)
    t.up()
    t.forward(l/2)
    t.down()
    t.begin_fill()
    #on dessine le premier cercle
    t.circle(l/10)
    t.end_fill()
    t.left(90)
    t.forward(l/10*2)
    t.left(90)
    t.forward(l/10)
    t.setheading(0)
    #on dessine les deux cercles du dessus
    for i in range(2):
        t.begin_fill()
        t.circle(l/10)
        t.end_fill()
        t.up()
        t.forward(l/10*2)
        t.down()
    t.left(90)
    t.up()
    t.forward(l/10*2)
    t.left(90)
    t.forward(l/10+l/10*4)
    t.down()
    t.setheading(0)
    #on dessine les trois cercles du dessus
    for i in range(3):
        t.begin_fill()
        t.circle(l/10)
        t.end_fill()
        t.up()
        t.forward(l/10*2)
        t.down()
    t.left(90)
    t.up()
    t.forward(l/10*2)
    t.left(90)
    t.forward(l/10+l/10*3)
    t.down()
    t.setheading(90) 
    t.circle(l/3,30)
    t.setheading(0)

#fonction qui dessine l'objet poire
def poire(x,y,l,c,t):
    deplacement(x+l/1.5,y,t)
    t.color(c)
    t.begin_fill()
    t.circle(l)
    t.end_fill()
    t.begin_fill()
    t.left(120)
    t.forward(l/0.58)
    t.setheading(0)
    t.begin_fill()
    t.left(72)
    t.forward(l*2)
    t.right(110)
    t.color("white")
    t.circle(l,70)
    t.left(110)
    t.circle(l,70)
    t.setheading(0)
    t.color(c)
    t.right(60)
    t.forward(l*2)
    t.end_fill()
    t.setheading(0)
